version: '3.8'

networks:
  app-tier:
    external: true

services:
  php:
    image:       devilbox/php-fpm:8.0-work-0.123
    working_dir: /application
    environment:
      APP_ENV:  'local'
      TIMEZONE: 'Asia/Almaty'
    volumes:
      - ${PWD}/advertising:/application
      - ${PWD}/configurations/php.ini:/etc/php-custom.d/php.ini
    ports:
      - 9000
    restart:     unless-stopped
    networks:
      - app-tier

  nginx:
    image: nginx
    ports:
      - 8811:80
    volumes:
      - ${PWD}/configurations/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ${PWD}/advertising:/application
    networks:
      - app-tier

  mysql:
    image:   mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      eskimi
      MYSQL_USER:          eskimi
      MYSQL_PASSWORD:      eskimi
    volumes:
      - ${PWD}/mysql-data:/var/lib/mysql
    ports:
    - 33036:3306
    networks:
      - app-tier
